

https://www.cnblogs.com/daliangtou/p/5423914.html

./img/django_many_to_many_error.jpg

Direct assignment to the forward side of a many-to-many set is prohibited. Use user.set() instead.

needs to have a value for field "id" before this many-to-many relationship can be used.